let products = [
	{
		id: 1001,
		title: "Quadratic Equations",
		description: "In this class learn how to do Quadratic Equations",
		price: 60,
		image: "img/quadtraticform.jpg",
		availableInventory: 5,
		Subject: "Math",
        Location: "Grove",
	},
	{
		id: 1002,
		title: "Algebra",
		description: "In this class learn how to do Algebra",
		price: 40,
		image: "img/algebra.jpg",
		availableInventory: 2,
		Subject: "Math",
        Location: "HatchCroft",
	},
    {
		id: 1003,
		title: "Ionic Bonds",
		description: "In this class learn how to do Ionic Bonds",
		price: 80,
		image: "img/ionic.png",
		availableInventory: 6,
		Subject: "Science",
        Location: "Fenella",
	},
    {
		id: 1004,
		title: "Physics Basics",
		description: "In this class learn about the basics of physics",
		price: 20,
		image: "img/physics.jpeg",
		availableInventory: 6,
		Subject: "Science",
        Location: "Grove",
	},
    {
		id: 1005,
		title: "English Literature",
		description: "In this class learn about classic English books",
		price: 60,
		image: "img/englishliturature.png",
		availableInventory: 6,
		Subject: "English",
        Location: "Hendon Public Library",
	},
    {
		id: 1006,
		title: "English Language",
		description: "In this class learn about the english Language",
		price: 60,
		image: "img/englishlang.jpeg",
		availableInventory: 6,
		Subject: "English",
        Location: "Hendon Public Library",
	},
    {
		id: 1007,
		title: "HTML",
		description: "In this class learn how to program HTML",
		price: 60,
		image: "img/html.png",
		availableInventory: 6,
		Subject: "Computer Science",
        Location: "Williams Building",
	},
    {
		id: 1008,
		title: "Python",
		description: "In this class learn about python",
		price: 60,
		image: "img/python.png",
		availableInventory: 6,
		Subject: "Computer Science",
        Location: "Vine",
	},
    {
		id: 1009,
		title: "Piano",
		description: "In this class learn how to play the piano",
		price: 60,
		image: "img/piano.png",
		availableInventory: 6,
		Subject: "Music",
        Location: "Vine",
	},
    {
		id: 1010,
		title: "Recorder",
		description: "In this class learn how to play the recorder",
		price: 60,
		image: "img/recorder.png",
		availableInventory: 6,
		Subject: "Music",
        Location: "Fenella",
	},


];
